#pragma once

#define DELTA_TIME 0.018f

#define FISH_COUNT 400
#define FISH_SPEED 50.0f
#define NEARBY_DISTANCE		15.0f	// how far boids can see


#define COHESION_MAX_DISTANCE 15.0f
#define SEPARATION_MIN_DISTANCE 0.5f

#define ALIGNMENT_STRENGTH 2.0f
#define SEPARATION_STRENGTH 1.4f
#define COHESION_STRENGTH 1.5f

#define DIRECTION_MODIFIER_ANGLE 0.3f